[package]
name = "module-single-author-public-read-no-upgrades"
version = "0.1.0-alpha.1"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
leaf-module-sdk = { path = "../../leaf-module-sdk" }

serde_json = "1.0.143"
