[package]
name = "leaf-module-public-read-write-admin-upgrade"
version = "0.1.0-alpha.1"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
leaf-module-sdk = { path = "../../leaf-module-sdk" }
parity-scale-codec = { version = "3.7.5" }
