[package]
name = "leaf-module-sdk"
version = "0.1.0-alpha.1"

description.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
leaf-stream-types = { version = "0.1.0-alpha.1", path = "../leaf-stream-types" }
anyhow = "1.0.99"
